apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-httpd
spec:
  replicas: 5
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend-container
          image: httpd
          ports:
            - containerPort: 80
              protocol: TCP
